
class items:

    def get_colors(self):
        color_list = """
        aquamarine, azure,
            black, blue,
            blueviolet, brown, burlywood, cadetblue,
            chartreuse, chocolate, coral, cornflowerblue,
            crimson, cyan, darkblue, darkcyan,
            darkgoldenrod, darkgray, darkgrey, darkgreen,
            darkkhaki, darkmagenta, darkolivegreen, darkorange,
            darkorchid, darkred, darksalmon, darkseagreen,
            darkslateblue, darkslategray, darkslategrey,
            darkturquoise, darkviolet, deeppink, deepskyblue,
            dimgray, dimgrey, dodgerblue, firebrick,
            floralwhite, forestgreen, fuchsia, gainsboro,
            ghostwhite, gold, goldenrod, gray, grey, green,
            greenyellow, honeydew, hotpink, indianred, indigo,
            ivory, khaki, lavender, lavenderblush, lawngreen,
            lemonchiffon, lightblue, lightcoral, lightcyan,
            lightgoldenrodyellow, lightgray, lightgrey,
            lightgreen, lightpink, lightsalmon, lightseagreen,
            lightskyblue, lightslategray, lightslategrey,
            lightsteelblue, lightyellow, lime, limegreen,
            linen, magenta, maroon, mediumaquamarine,
            mediumblue, mediumorchid, mediumpurple,
            mediumseagreen, mediumslateblue, mediumspringgreen,
            mediumturquoise, mediumvioletred, midnightblue,
            mintcream, mistyrose, moccasin, navajowhite, navy,
            oldlace, olive, olivedrab, orange, orangered,
            orchid, palegoldenrod, palegreen, paleturquoise,
            palevioletred, papayawhip, peachpuff, peru, pink,
            plum, powderblue, purple, red, rosybrown,
            royalblue, rebeccapurple, saddlebrown, salmon,
            sandybrown, seagreen, seashell, sienna, silver,
            skyblue, slateblue, slategray, slategrey, snow,
            springgreen, steelblue, tan, teal, thistle, tomato,
            turquoise, violet, wheat, white, whitesmoke,
            yellow, yellowgreen
            """.split()
        return color_list
    def get_genres(self):
        return ['acoustic', 'afrobeat', 'alt-rock', 'alternative', 
                'ambient', 'anime', 'black-metal', 'bluegrass', 'blues', 
                'bossanova', 'brazil', 'breakbeat', 'british', 'cantopop', 
                'chicago-house', 'children', 'chill', 'classical', 'club', 
                'comedy', 'country', 'dance', 'dancehall', 'death-metal', 
                'deep-house', 'detroit-techno', 'disco', 'disney', 
                'drum-and-bass', 'dub', 'dubstep', 'edm', 'electro', 
                'electronic', 'emo', 'folk', 'forro', 'french', 'funk', 
                'garage', 'german', 'gospel', 'goth', 'grindcore', 'groove',
                'grunge', 'guitar', 'happy', 'hard-rock', 'hardcore', 
                'hardstyle', 'heavy-metal', 'hip-hop', 'holidays', 'honky-tonk', 
                'house', 'idm', 'indian', 'indie', 'indie-pop', 'industrial',
                'iranian', 'j-dance', 'j-idol', 'j-pop', 'j-rock', 'jazz', 
                'k-pop', 'kids', 'latin', 'latino', 'malay', 'mandopop', 
                'metal', 'metal-misc', 'metalcore', 'minimal-techno', 'movies', 
                'mpb', 'new-age', 'new-release', 'opera', 'pagode', 'party', 
                'philippines-opm', 'piano', 'pop', 'pop-film', 'post-dubstep', 
                'power-pop', 'progressive-house', 'psych-rock', 'punk', 
                'punk-rock', 'r-n-b', 'rainy-day', 'reggae', 'reggaeton', 
                'road-trip', 'rock', 'rock-n-roll', 'rockabilly', 'romance',
                'sad', 'salsa', 'samba', 'sertanejo', 'show-tunes', 
                'singer-songwriter', 'ska', 'sleep', 'songwriter', 'soul', 
                'soundtracks', 'spanish', 'study', 'summer', 'swedish', 
                'synth-pop', 'tango', 'techno', 'trance', 'trip-hop', 'turkish',
                'work-out', 'world-music']
    def select_genres(self):
        return ['acoustic', 'alt-rock', 'alternative', 
                'ambient', 'anime', 'bluegrass', 'blues', 
                'chill', 'classical', 'club', 
                'country', 'dance', 
                'deep-house','disco', 
                'drum-and-bass', 'edm', 'electro', 
                'electronic', 'emo', 'folk',
                'goth','hard-rock'
                'heavy-metal', 'hip-hop', 'holidays',
                'house', 'indie'
                'jazz', 
                'k-pop', 'kids',
                'metal',
                'new-age','opera', 'party', 
                'piano', 'pop', 
                'punk', 
                'r-n-b', 'rainy-day', 'reggae',
                'rock-n-roll',
                'sad', 'salsa', 
                'sleep', 'soul', 
                'techno', 
                'work-out', 'world-music']